# Site settings
author: Mike White
title: The Docs will see you now
header-img: img/home-bg.png
email: michaeljwhite@gmail.com
copyright_name: Mike White
description: > # this means to ignore newlines until "baseurl:"
  A collection of love letters to our future selves.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  big32mike

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
